### PR TITLE
Fix support for --incompatible_disallow_empty_glob

### PR DESCRIPTION
**Pull request by keith**
This allows downstream repos to set this flag

### CODE REVIEW

**Review by rrbutani — COMMENTED** [review]
This change looks good but CI is failing on globs in deps (`openssl`): https://github.com/bazel-contrib/toolchains_llvm/actions/runs/9182559234/job/25251665225?pr=331#step:4:38

**Comment by rrbutani** [comment]
@keith would you mind adding `allow_empty` here?

https://github.com/bazel-contrib/toolchains_llvm/blob/be777a3a39dfe5f16ce6beda2062d50d71c74ebf/tests/openssl/openssl.bazel#L840-L845

**Comment by keith** [comment]
added! we'll see!

**Comment by rockwood-openai** [comment]
Ping on this, would be great to land it :)

**Pull request merged**
